# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: key_exchange.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='key_exchange.proto',
  package='',
  serialized_pb='\n\x12key_exchange.proto\"g\n\x0bKeyExchange\x12\x14\n\x0c\x63lientPublic\x18\x01 \x01(\t\x12\x14\n\x0cserverPublic\x18\x02 \x01(\t\x12\x15\n\rclientSending\x18\x03 \x01(\t\x12\x15\n\rserverSending\x18\x04 \x01(\t')




_KEYEXCHANGE = _descriptor.Descriptor(
  name='KeyExchange',
  full_name='KeyExchange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientPublic', full_name='KeyExchange.clientPublic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serverPublic', full_name='KeyExchange.serverPublic', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clientSending', full_name='KeyExchange.clientSending', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serverSending', full_name='KeyExchange.serverSending', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=125,
)

DESCRIPTOR.message_types_by_name['KeyExchange'] = _KEYEXCHANGE

class KeyExchange(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _KEYEXCHANGE

  # @@protoc_insertion_point(class_scope:KeyExchange)


# @@protoc_insertion_point(module_scope)
